<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Iap\Module'                                => __DIR__ . '/Module.php',
  'Iap\Collector\IapCollector'              => __DIR__ . '/src/Iap/Collector/IapCollector.php',
  'Iap\Controller\UserController'             => __DIR__ . '/src/Iap/Controller/UserController.php',
  'Iap\Forms\Login'                           => __DIR__ . '/src/Iap/Forms/Login.php',
  'Iap\Provider\DbTable\DbIdentity'           => __DIR__ . '/src/Iap/Provider/DbTable/DbIdentity.php',
  'Iap\Provider\DbTable\DbTableProvider'      => __DIR__ . '/src/Iap/Provider/DbTable/DbTableProvider.php',
  'Iap\Provider\Interfaces\IdentityInterface' => __DIR__ . '/src/Iap/Provider/Interfaces/IdentityInterface.php',
  'Iap\Provider\Interfaces\ProviderInterface' => __DIR__ . '/src/Iap/Provider/Interfaces/ProviderInterface.php',
  'Iap\Provider\ProviderResult'               => __DIR__ . '/src/Iap/Provider/ProviderResult.php',
  'Iap\Service\Factory\Collector'             => __DIR__ . '/src/Iap/Service/Factory/Collector.php',
  'Iap\Service\Factory\Config'                => __DIR__ . '/src/Iap/Service/Factory/Config.php',
  'Iap\Service\Factory\Providers\DbTable'     => __DIR__ . '/src/Iap/Service/Factory/Providers/DbTable.php',
  'Iap\Service\Factory\Storage\Session'       => __DIR__ . '/src/Iap/Service/Factory/Storage/Session.php',
  'Iap\Service\Factory\Storage'               => __DIR__ . '/src/Iap/Service/Factory/Storage.php',
  'Iap\Service\Factory\IapService'          => __DIR__ . '/src/Iap/Service/Factory/IapService.php',
  'Iap\Service\IAServiceProvider'             => __DIR__ . '/src/Iap/Service/IAServiceProvider.php',
  'Iap\Storage\Session'                       => __DIR__ . '/src/Iap/Storage/Session.php',
);
